package com.geeksforless.fintech.model;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.validation.constraints.DecimalMin;
import java.math.BigDecimal;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Represents a financial account entity within the system.
 * This entity encapsulates the details of an account, including its unique identifier and balance.
 * It maps directly to a database table using JPA annotations.
 */
@Entity
@Data
@AllArgsConstructor
@NoArgsConstructor
public class Account {
    /**
     * The unique identifier of the account.
     * It's automatically generated by the database when a new account is created.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The current balance of the account.
     * It represents the amount of money in the account at any given time.
     */
    @DecimalMin(value = "0.0", inclusive = true, message = "Balance must not be less than 0")
    private BigDecimal balance;
}

